import {
  FaPython,
  FaAws,
  FaReact,
  FaNodeJs,
  FaJs,
  FaJava,
} from "react-icons/fa";
import {
  SiLua,
  SiRobloxstudio,
  SiTensorflow,
  SiRedis,
  SiSolidity,
  SiEthereum,
  SiMongodb,
  SiExpress,
  SiCocos,
  SiTypescript,
  SiJest,
  SiNextdotjs,
  SiBlender,
} from "react-icons/si";
import { TbBrandCSharp } from "react-icons/tb";
import { BsUnity } from "react-icons/bs";
import { RiSupabaseLine } from "react-icons/ri";

export const skillIcons = {
  Python: FaPython,
  TensorFlow: SiTensorflow,
  AWS: FaAws,
  Redis: SiRedis,
  Solidity: SiSolidity,
  Ethereum: SiEthereum,
  React: FaReact,
  "Node.js": FaNodeJs,
  "React Native": FaReact,
  "C++": FaJs,
  MongoDB: SiMongodb,
  "Express.js": SiExpress,
  "D3.js": FaJs,
  Javascript: FaJs,
  Unity: BsUnity,
  JEST: SiJest,
  "Cocos Creator": SiCocos,
  Typescript: SiTypescript,
  "C#": TbBrandCSharp,
  NextJS: SiNextdotjs,
  Supabase: RiSupabaseLine,
  SmartFoxServer: FaJava,
  Java: FaJava,
  Lua: SiLua,
  RobloxStudio: SiRobloxstudio,
  Blender: SiBlender,
};
